FROM golang:1.21.3 as maker

# Set the Current Working Directory inside the container
WORKDIR /app
ENV BRANCH=main
RUN git clone --branch $BRANCH https://github.com/bitcoin-sv/arc.git

RUN go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@latest
RUN go install -v honnef.co/go/tools/cmd/staticcheck@latest

WORKDIR /app/arc/test

# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed
RUN go mod download

# This will compile and run the tests
CMD [ "go", "test", "-v", "-failfast" ,"./..."]
